sudo: false
language: node_js
node_js:
- '6'
- '8'
- '10'
os:
- osx
- linux
before_install:
- npm install -g typescript
- npm install -g codecov
install:
- |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    export DISPLAY=':99.0';
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & 
  fi
- npm install
- npm run vscode:prepublish
script:
- npm test
after_success:
- bash < (curl -s https://codecov.io/bash)
